/**/controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mobile_robot_controller:
      type: diff_drive_controller/DiffDriveController

/**/mobile_robot_controller:
  ros__parameters:
    left_wheel_names: ["base_lf", "base_lb"]
    right_wheel_names: ["base_rf", "base_rb"]
    wheels_per_side: 2
    use_stamped_vel: true
    publish_rate: 1000.0
    pose_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_radius: 0.02
    wheel_separation: 0.15
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    wheel_separation_multiplier: 1.0

    cmd_vel_timeout: 1.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    # publish_limited_velocity: true
    # publish_wheel_data: true
    enable_odom_tf: true

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 4.0
    linear.x.min_velocity: -4.0
    linear.x.max_acceleration: 1.8


    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 4.7
    angular.z.min_velocity: -4.7
    angular.z.max_acceleration: 1.8
    angular.z.min_acceleration: -0.8


